/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { Html, PresentationControls, useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useControls } from "leva";
import { gsap } from "gsap";
import * as THREE from "three";
import useAnimationStore from "../Store/AnimationState";
const colorArray = [
  {
    name: "cool green",
    hex: "#D8E8D3",
    imageUrl: "/assets/color_1.png",
  },
  {
    name: "Jade Black",
    hex: "#191a1c",
    imageUrl: "/assets/color_2.png",
  },
  {
    name: "Moon White",
    hex: "#E0DDE6",
    imageUrl: "/assets/color_3.png",
  },
];

export function Model(props) {
  const { nodes, materials } = useGLTF("/Models/N3BLACK.glb");
  const { camera, gl, scene } = useThree();
  const activeState = useAnimationStore((state) => state.activeState);

  const [color, setColor] = useState("#D8E8D3");
  const groupRef = useRef();

  useEffect(() => {
    props.setModelLoaded(true);
    // Animation timeline using gsap
    const timeline = gsap.timeline();

    // Initial spinning animation with movement
    timeline.to(groupRef.current.position, {
      x: 0,
      z: 0.4,
      duration: -10,
      ease: "power1.inOut",
      onUpdate: () => {
        groupRef.current.rotation.y += 0.1;
      },
    });

    timeline.to({}, { duration: 1 });
  }, []);

  useEffect(() => {
    if (activeState === 3) {
      gsap.to(groupRef.current.position, {
        x: 0.1,
        y: -0.5,
        z: -8.6,
        duration: 1,
        onStart: () => {
          gsap.to(groupRef.current.rotation, {
            x: 0,
            y: 2.6,
            z: 0,
            duration: 1,
          });
        },
      });
    } else if (activeState === 2) {
      gsap.to(groupRef.current.position, {
        x: 1.2,
        y: 0.2,
        z: -8.6,
        duration: 1,
        onStart: () => {
          gsap.to(groupRef.current.rotation, {
            x: window.innerWidth < 440 ? -0.4 : 0,
            y: -3.8,
            z: 0,
            duration: 1,
          });
        },
      });
    } else if (activeState === 1) {
      gsap.to(groupRef.current.rotation, {
        y: Math.PI * 2,
        x: 0,
        z: 0,

        duration: 1,
      });
    } else if (activeState === 0) {
      gsap.to(groupRef.current.position, {
        x: 0,
        y: 0.4,
        z: -10,
        duration: 1,
        onStart: () => {
          gsap.to(groupRef.current.rotation, {
            x: window.innerWidth < 440 ? -0.4 : 0,
            y: Math.PI,
            z: 0,
            duration: 1,
          });
        },
      });
    }
  }, [activeState]);

  // const { position, rotation } = useControls("Camera", {
  //   position: { value: [0.9, 0.2, -8.6], step: 0.1 },
  //   rotation: { value: [-0.5, 0.3, 0.4], step: 0.01 },
  // });
  return (
    <group>
      {activeState === 1 && (
        <Html position={[window.innerWidth < 440 ? -0.3 : 0, 0, -9]}>
          <div className='color-container'>
            <span
              className='color-header'
              style={{
                top: window.innerWidth < 440 ? "77%" : "80%",
              }}
            >
              {colorArray.filter((item) => item.hex === color)[0].name}
            </span>

            <img
              src='/assets/color_1.png'
              onClick={() => setColor("#D8E8D3")}
              className={`color-div ${
                color === "#D8E8D3" && "color-div-selected"
              } `}
            />
            <img
              src='/assets/color_2.png'
              onClick={() => setColor("#191a1c")}
              className={`color-div ${
                color === "#191a1c" && "color-div-selected"
              } `}
            />
            <img
              src='/assets/color_3.png'
              onClick={() => setColor("#E0DDE6")}
              className={`color-div ${
                color === "#E0DDE6" && "color-div-selected"
              } `}
            />
          </div>
        </Html>
      )}
      {groupRef.current && (activeState === 0 || activeState === 1) && (
        <CustomOrbitControl object={groupRef} />
      )}
      <group
        // position={position}
        // rotation={rotation}
        {...props}
        dispose={null}
        scale={0.03}
        ref={groupRef}
      >
        <mesh
          geometry={nodes.Body10.geometry}
          material={materials["F_dded1460bc804eb2aae86975d35283e5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body100.geometry}
          material={materials["F_ff6f39f3fe1649fc8e3e6f6c3e04bee9.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body101.geometry}
          material={materials["F_9bc43e7aa9614a508beb92dc0e33a4a4.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body102.geometry}
          material={materials["F_ff6f39f3fe1649fc8e3e6f6c3e04bee9.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body103.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body104.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body105.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body106.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          name='back'
          material-color={activeState === 1 ? color : "#dfebf7"}
          material-roughness={0.8}
          geometry={nodes.Body106001.geometry}
          material={materials["Metallic-22 (Dark Blue)"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body107.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body108.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body109.geometry}
          material={materials["F_ff6f39f3fe1649fc8e3e6f6c3e04bee9.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body11.geometry}
          material={materials["F_dded1460bc804eb2aae86975d35283e5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body110.geometry}
          material={materials["F_f9d4f6b0e246426c9f0c3472ad3a8c3b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body110001.geometry}
          material={materials["F_b9f912fd340c429c991eb738164d1025.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body111.geometry}
          material={materials["F_458a603c6efb4472a395328a3283ed37.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body112.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body113.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body114.geometry}
          material={materials["F_94b8d84eae0442a7b57c70fe413c2b00.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body114001.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body115.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body116.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body117.geometry}
          material={materials["F_45d30b3cf9aa40c69e8ef5c83dac2e07.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body118.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body119.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body12.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body120.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body121.geometry}
          material={materials["F_45d30b3cf9aa40c69e8ef5c83dac2e07.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body122.geometry}
          material={materials["F_10e2b58c074a4bc4be8521c005b4be13.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body123.geometry}
          material={materials["F_5ecc5d0bb04a4eb883e76ee53cd973a8.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body124.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body125.geometry}
          material={materials["F_77f0e28fe93f4db9831dc294faa25f57.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body126.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body127.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body128.geometry}
          material={materials["F_a3e8523e359849d0be6a1c336827341b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body129.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body13.geometry}
          material={materials["F_89922a4808a14689ae647d93c632d245.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body130.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body131.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body132.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body133.geometry}
          material={materials["F_8b3d329d088c447b92ecb93ea2118772.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body134.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body135.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body136.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body137.geometry}
          material={materials["F_e71909415ae04ccba71ca654d278bf4d.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body137001.geometry}
          material={materials["F_e46f7d65b68c4a4e92e9111e5d86d288.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body137002.geometry}
          material={materials["F_a110f8e34d154909a89f5340eb9c14e2.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body138.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body139.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body14.geometry}
          material={materials["F_05ac4422a26641e7b2e0be16946d296b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body140.geometry}
          material={materials["F_94b8d84eae0442a7b57c70fe413c2b00.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body140001.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.CAMERA.geometry}
          material={materials["my glass"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body142.geometry}
          material={materials["F_8b3d329d088c447b92ecb93ea2118772.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body143.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body144.geometry}
          material={materials["F_94b8d84eae0442a7b57c70fe413c2b00.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body144001.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body145.geometry}
          material={materials["side black.002"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body146.geometry}
          material={materials["side black.002"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body147.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body148.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body149.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15.geometry}
          material={materials["F_4ad74e5ff2d443338298248e8871cf18.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15001.geometry}
          material={materials["F_094801c1d0574ed695a653a3df34e52f.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15002.geometry}
          material={materials["F_3ffe4927dd5440e0b5a4163b8933b921.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15003.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15004.geometry}
          material={materials["F_1eb0acc19ea84ac9bd48b41bef3e792b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15005.geometry}
          material={materials["F_3c18c3f8bab24416a1871cc8b9e448b2.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15006.geometry}
          material={materials["F_d9f18555bfe646539211c18d946dd5ee.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15007.geometry}
          material={materials["F_60ff2faad5b54a0786310027b4a0df86.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15008.geometry}
          material={materials["F_5518fc395ab24e80a2acf67602c227f8.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15009.geometry}
          material={materials["F_aba3b44438e44c6ab0e6d332a1fbd161.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15010.geometry}
          material={materials["F_4c9e0fb6b010416d845508adf53bf199.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15011.geometry}
          material={materials["F_10e2b58c074a4bc4be8521c005b4be13.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15012.geometry}
          material={materials["F_4e7cd1005ac844289efaf40ecf3460c0.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15013.geometry}
          material={materials["F_f47e7e4ae77c4fe9bdf79078ed5318fc.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15014.geometry}
          material={materials["F_a761a0fc409d407bbf94b54bd9db64b5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body15015.geometry}
          material={materials["F_f845fe47a0d144aeb1244aef02649e31.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body150.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body151.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body152.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body153.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body153001.geometry}
          material={materials["side black.002"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body154.geometry}
          material={materials["F_0d6f7579558242b1bcf45b05bb5ad86b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body155.geometry}
          material={materials["F_29c822fe2457409aafaafda23e069b98.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body156.geometry}
          material={materials["side black.002"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body157.geometry}
          material={materials["F_4ed2b4ae5f9d4f7f983daed308a5bcda.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body158.geometry}
          material={materials["F_4e176b8dabe741dcae6f1e5cc45c46ac.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body159.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body16.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body160.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body161.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body162.geometry}
          material={materials["F_94b8d84eae0442a7b57c70fe413c2b00.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body163.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body164.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body165.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body166.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body167.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body168.geometry}
          material={materials["F_77f0e28fe93f4db9831dc294faa25f57.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body169.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body17.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body170.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body171.geometry}
          material={materials["F_5979a70572c7464aaed0967acabe31b5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body171001.geometry}
          material={materials["F_209379a048ae4daca22386b4dbd6cf29.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body171002.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body172.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body173.geometry}
          material={materials["F_77f0e28fe93f4db9831dc294faa25f57.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body174.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body175.geometry}
          material={materials["F_45d30b3cf9aa40c69e8ef5c83dac2e07.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body176.geometry}
          material={materials["F_10e2b58c074a4bc4be8521c005b4be13.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body177.geometry}
          material={materials["F_0d6f7579558242b1bcf45b05bb5ad86b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body178.geometry}
          material={materials["F_edc700d862c74514bba1d393a83f3968.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body178001.geometry}
          material={materials["F_10e2b58c074a4bc4be8521c005b4be13.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body179.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body18.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body180.geometry}
          material={materials["F_5979a70572c7464aaed0967acabe31b5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body181.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body182.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body183.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body184.geometry}
          material={materials["F_495df97818764f03bd6bcb8b6292c9c3.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body185.geometry}
          material={materials["F_495df97818764f03bd6bcb8b6292c9c3.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body185001.geometry}
          material={materials["F_89922a4808a14689ae647d93c632d245.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body186.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body187.geometry}
          material={materials["F_0d6f7579558242b1bcf45b05bb5ad86b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body188.geometry}
          material={materials["F_4ad74e5ff2d443338298248e8871cf18.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body189.geometry}
          material={materials["F_794a05a7f5614cb6b53c9d3fb01a561f.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body19.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body190.geometry}
          material={materials["F_4ad74e5ff2d443338298248e8871cf18.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body191.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body192.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body193.geometry}
          material={materials["F_3b2d5c35777d404eb88795b0c9766565.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body194.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body195.geometry}
          material={materials["F_8b3d329d088c447b92ecb93ea2118772.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body196.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body197.geometry}
          material={materials["F_794a05a7f5614cb6b53c9d3fb01a561f.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body197001.geometry}
          material={materials["shiney white gold"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body198.geometry}
          material={materials["F_10e2b58c074a4bc4be8521c005b4be13.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body199.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body2.geometry}
          material={materials["side black.003"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body20.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body200.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body201.geometry}
          material={materials["F_bed7b1c9643247f2a97a2466d0e15ba7.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body201001.geometry}
          material={materials["F_96e04fc7d00b40c3b1b36956612d3eb4.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body202.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body203.geometry}
          material={materials["F_4ad74e5ff2d443338298248e8871cf18.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body204.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body205.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body206.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body21.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body22.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body23.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body24.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body25.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body26.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body27.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body28.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body29.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body3.geometry}
          material={materials["side black.003"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body30.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body31.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body32.geometry}
          material={materials["F_05f3fa05f9834aa5ab8a17cae983a096.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body33.geometry}
          material={materials["F_cb1bb2226ccf4b7fbc80e811eb88ab7e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body34.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body35.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.SCREEN_1.geometry}
          material={materials["F_073b46fb7b514276a3e5f9df98067f87.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body37.geometry}
          material={materials["F_a3e8523e359849d0be6a1c336827341b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body37001.geometry}
          material={materials["F_89922a4808a14689ae647d93c632d245.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body37002.geometry}
          material={materials["F_1761b34f960f4cfb9d97f01162b860a7.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body39.geometry}
          material={materials["F_235e85bdfea3450599596d41bd2a32c8.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body4.geometry}
          material={materials["side black.003"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body40.geometry}
          material={materials["F_89922a4808a14689ae647d93c632d245.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body41.geometry}
          material={materials["F_89922a4808a14689ae647d93c632d245.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body42.geometry}
          material={materials["F_c3d7e9fe1312479b858448548bcaa9bb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body43.geometry}
          material={materials["F_c9d0cb8f556949febf559d688ce02983.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body44.geometry}
          material={materials["F_63b3e711074e47fc91548d6f2e32583e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body45.geometry}
          material={materials["Rear glass"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body46.geometry}
          material={materials["F_61161eaa534f4f7eb7c524cef8b167d7.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body47.geometry}
          material={materials["Metallic-22 (Dark Blue)"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body48.geometry}
          material={materials["F_76e89297d7154893baf06ac2df6a4951.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body49.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body5.geometry}
          material={materials["F_dded1460bc804eb2aae86975d35283e5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body50.geometry}
          material={materials["F_cbe9c6b5f885484194eee84c378d20fc.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body51.geometry}
          material={materials["F_3b2d5c35777d404eb88795b0c9766565.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body52.geometry}
          material={materials["F_00be1b89e8c84f6082c71308039968d0.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body53.geometry}
          material={materials["F_0d6f7579558242b1bcf45b05bb5ad86b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body54.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body55.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body56.geometry}
          material={materials["F_8b3d329d088c447b92ecb93ea2118772.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body58.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body59.geometry}
          material={materials["F_10e2b58c074a4bc4be8521c005b4be13.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body6.geometry}
          material={materials["F_dded1460bc804eb2aae86975d35283e5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body60.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body61.geometry}
          material={materials["F_0d6f7579558242b1bcf45b05bb5ad86b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body62.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body63.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body64.geometry}
          material={materials["F_235e85bdfea3450599596d41bd2a32c8.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body64001.geometry}
          material={materials["F_69b6c25709f3491c8291ad76468b01a0.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body65.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body66.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body67.geometry}
          material={materials["F_0d6f7579558242b1bcf45b05bb5ad86b.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body68.geometry}
          material={materials["side black.002"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body69.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body7.geometry}
          material={materials["F_dded1460bc804eb2aae86975d35283e5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body70.geometry}
          material={materials["F_13655a26260e42048e07fc9a22cf89c0.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body71.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body72.geometry}
          material={materials["F_8b3d329d088c447b92ecb93ea2118772.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body73.geometry}
          material={materials["F_8b3d329d088c447b92ecb93ea2118772.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body73001.geometry}
          material={materials["Metallic-22 (Dark Blue)"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body74.geometry}
          material={materials["F_77f0e28fe93f4db9831dc294faa25f57.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body75.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body76.geometry}
          material={materials["side black.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body77.geometry}
          material={materials["F_37bac7aa9c20446682f63b6f318da540.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body77001.geometry}
          material={materials["F_edc700d862c74514bba1d393a83f3968.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body77002.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body77003.geometry}
          material={materials["F_7ecb926b2a054dc58a9f9fd0094215b3.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body77004.geometry}
          material={materials["F_235e85bdfea3450599596d41bd2a32c8.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body77005.geometry}
          material={materials["F_922aa139003d4bd6aa288a71fff86599.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body78.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body79.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body8.geometry}
          material={materials["F_dded1460bc804eb2aae86975d35283e5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body80.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body81.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body82.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body83.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body84.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body85.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body86.geometry}
          material={materials["F_ff6f39f3fe1649fc8e3e6f6c3e04bee9.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body87.geometry}
          material={materials["F_ff6f39f3fe1649fc8e3e6f6c3e04bee9.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body88.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body89.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body9.geometry}
          material={materials["F_dded1460bc804eb2aae86975d35283e5.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body90.geometry}
          material={materials["F_ff6f39f3fe1649fc8e3e6f6c3e04bee9.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body91.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body92.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body93.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body94.geometry}
          material={materials["F_4f7d018092914913ae6bb262318eade6.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body95.geometry}
          material={materials["F_cf09f42c14bd43d4b3c6aff59746b42e.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body96.geometry}
          material={materials["F_ff6f39f3fe1649fc8e3e6f6c3e04bee9.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body97.geometry}
          material={materials["F_8b3d329d088c447b92ecb93ea2118772.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body98.geometry}
          material={materials["F_cc923a3c4a1d4e2387f0a5398ea156ea.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
        <mesh
          geometry={nodes.Body99.geometry}
          material={materials["F_91b860ee3db7476bb91f102d2aa76ffb.001"]}
          position={[0.55, 0.18, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={10}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/N3BLACK-transformed.glb");

const CustomOrbitControl = ({ object }) => {
  const { gl, camera } = useThree();
  let isDragging = false;
  const previousMouse = useRef([0, 0]);
  const activeState = useAnimationStore((state) => state.activeState);

  const onMouseDown = (event) => {
    isDragging = true;
    previousMouse.current =
      event.type === "touchstart"
        ? [event.touches[0].clientX, event.touches[0].clientY]
        : [event.clientX, event.clientY];
  };

  const onMouseUp = () => {
    isDragging = false;
  };

  const onMouseMove = (event) => {
    if (!isDragging) return;
    const clientX =
      event.type === "touchmove" ? event.touches[0].clientX : event.clientX;
    const clientY =
      event.type === "touchmove" ? event.touches[0].clientY : event.clientY;
    const deltaMove = [
      clientX - previousMouse.current[0],
      clientY - previousMouse.current[1],
    ];

    const deltaRotationQuaternion = new THREE.Quaternion().setFromEuler(
      new THREE.Euler(
        toRadians(deltaMove[1]),
        toRadians(deltaMove[0]),
        0,
        "XYZ"
      )
    );

    object.current.quaternion.multiplyQuaternions(
      deltaRotationQuaternion,
      object.current.quaternion
    );

    previousMouse.current = [clientX, clientY];
  };

  const toRadians = (angle) => {
    return angle * (Math.PI / 180);
  };
  useFrame(() => {
    if (!isDragging && activeState !== 1) object.current.rotateY(0.005);
  });

  useEffect(() => {
    gl.domElement.addEventListener("mousedown", onMouseDown);
    window.addEventListener("mouseup", onMouseUp);
    gl.domElement.addEventListener("mousemove", onMouseMove);

    window.addEventListener("touchstart", onMouseDown);
    window.addEventListener("touchend", onMouseUp);
    window.addEventListener("touchmove", onMouseMove);
  }, []);

  return null;
};
